-- =============================================================================
-- V15__auditoria.sql
-- Auditoría: quién creó, modificó, aprobó o eliminó información y cuándo.
-- Implementado con triggers reales de Postgres (no solo en el código Java) para
-- que quede registrado incluso si algo escribe directo a la base sin pasar por
-- el backend. Cada trigger usa to_jsonb(OLD)/to_jsonb(NEW) para guardar el
-- antes/después completo de la fila -- "aprobar" o "rechazar" una solicitud no
-- son más que un UPDATE de su columna estado, así que quedan capturados como
-- MODIFICAR con el diff mostrando exactamente ese cambio (estado ENVIADA -> APROBADA).
--
-- "Quién": el trigger lee el GUC de sesión presus.usuario_actual, que el backend
-- fija con set_config(..., true) (alcance de la transacción actual) justo antes de
-- cada operación relevante -- ver AuditoriaService.marcarActorActual(). Si nadie lo
-- fijó (p.ej. una migración o un script directo), usuario_id queda NULL: la fila de
-- auditoría sigue existiendo, solo sin autor identificado.
-- =============================================================================

CREATE TABLE presus.auditoria (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    tabla VARCHAR(60) NOT NULL,
    registro_id BIGINT,
    accion VARCHAR(20) NOT NULL,
    usuario_id BIGINT,
    usuario_nombre VARCHAR(200),
    fecha TIMESTAMP(6) NOT NULL DEFAULT now(),
    datos_anteriores JSONB,
    datos_nuevos JSONB,
    PRIMARY KEY (id)
);

CREATE INDEX ix_auditoria_tabla_fecha ON presus.auditoria (tabla, fecha DESC);
CREATE INDEX ix_auditoria_usuario ON presus.auditoria (usuario_id);
CREATE INDEX ix_auditoria_fecha ON presus.auditoria (fecha DESC);

-- ── Función genérica: sirve para cualquier tabla cuya PK se llame "id" ─────────
CREATE OR REPLACE FUNCTION presus.fn_auditoria_generica() RETURNS TRIGGER AS $$
DECLARE
    v_usuario_id BIGINT;
    v_usuario_nombre VARCHAR(200);
    v_accion VARCHAR(20);
    v_registro_id BIGINT;
    v_nuevo JSONB;
    v_anterior JSONB;
BEGIN
    v_usuario_id := NULLIF(current_setting('presus.usuario_actual', true), '')::BIGINT;
    IF v_usuario_id IS NOT NULL THEN
        SELECT (nombre || ' ' || apellido) INTO v_usuario_nombre FROM presus.usuarios WHERE id = v_usuario_id;
    END IF;

    IF TG_OP = 'INSERT' THEN
        v_nuevo := to_jsonb(NEW);
        -- Nunca se guarda el hash de contraseña en la auditoría: es un log potencialmente
        -- expuesto por la UI de administración, y aunque sea un hash bcrypt (no texto plano),
        -- no hay razón para aumentar la superficie de ataque guardándolo donde no hace falta.
        IF TG_TABLE_NAME = 'usuarios' THEN v_nuevo := v_nuevo - 'password'; END IF;
        v_accion := 'CREAR';
        v_registro_id := (v_nuevo->>'id')::BIGINT;
        INSERT INTO presus.auditoria (tabla, registro_id, accion, usuario_id, usuario_nombre, datos_nuevos)
        VALUES (TG_TABLE_NAME, v_registro_id, v_accion, v_usuario_id, v_usuario_nombre, v_nuevo);
        RETURN NEW;
    ELSIF TG_OP = 'UPDATE' THEN
        v_anterior := to_jsonb(OLD);
        v_nuevo := to_jsonb(NEW);
        IF TG_TABLE_NAME = 'usuarios' THEN
            v_anterior := v_anterior - 'password';
            v_nuevo := v_nuevo - 'password';
        END IF;
        v_accion := 'MODIFICAR';
        v_registro_id := (v_nuevo->>'id')::BIGINT;
        INSERT INTO presus.auditoria (tabla, registro_id, accion, usuario_id, usuario_nombre, datos_anteriores, datos_nuevos)
        VALUES (TG_TABLE_NAME, v_registro_id, v_accion, v_usuario_id, v_usuario_nombre, v_anterior, v_nuevo);
        RETURN NEW;
    ELSIF TG_OP = 'DELETE' THEN
        v_anterior := to_jsonb(OLD);
        IF TG_TABLE_NAME = 'usuarios' THEN v_anterior := v_anterior - 'password'; END IF;
        v_accion := 'ELIMINAR';
        v_registro_id := (v_anterior->>'id')::BIGINT;
        INSERT INTO presus.auditoria (tabla, registro_id, accion, usuario_id, usuario_nombre, datos_anteriores)
        VALUES (TG_TABLE_NAME, v_registro_id, v_accion, v_usuario_id, v_usuario_nombre, v_anterior);
        RETURN OLD;
    END IF;
    RETURN NULL;
END;
$$ LANGUAGE plpgsql;

-- ── Variante para presus.rol_permisos: clave compuesta (rol_id, permiso_id), sin
--    columna "id" -- se audita por rol_id, que es la unidad de negocio real
--    ("a qué rol se le tocaron los permisos"), no por cada fila individual. ────
CREATE OR REPLACE FUNCTION presus.fn_auditoria_rol_permisos() RETURNS TRIGGER AS $$
DECLARE
    v_usuario_id BIGINT;
    v_usuario_nombre VARCHAR(200);
BEGIN
    v_usuario_id := NULLIF(current_setting('presus.usuario_actual', true), '')::BIGINT;
    IF v_usuario_id IS NOT NULL THEN
        SELECT (nombre || ' ' || apellido) INTO v_usuario_nombre FROM presus.usuarios WHERE id = v_usuario_id;
    END IF;

    IF TG_OP = 'INSERT' THEN
        INSERT INTO presus.auditoria (tabla, registro_id, accion, usuario_id, usuario_nombre, datos_nuevos)
        VALUES ('rol_permisos', NEW.rol_id, 'ASIGNAR_PERMISO', v_usuario_id, v_usuario_nombre, to_jsonb(NEW));
        RETURN NEW;
    ELSIF TG_OP = 'DELETE' THEN
        INSERT INTO presus.auditoria (tabla, registro_id, accion, usuario_id, usuario_nombre, datos_anteriores)
        VALUES ('rol_permisos', OLD.rol_id, 'QUITAR_PERMISO', v_usuario_id, v_usuario_nombre, to_jsonb(OLD));
        RETURN OLD;
    END IF;
    RETURN NULL;
END;
$$ LANGUAGE plpgsql;

-- ── Triggers en las tablas de mayor valor auditable: identidad/acceso
--    (usuarios, roles_usuario, rol_permisos, permisos) y el flujo de negocio
--    crítico (solicitud, actas, evaluaciones_finales). No se instrumentan las
--    ~40 tablas del esquema -- son las que responden "quién creó/modificó/
--    aprobó/eliminó información" en el sentido que importa para el sistema. ──
CREATE TRIGGER trg_auditoria_usuarios
    AFTER INSERT OR UPDATE OR DELETE ON presus.usuarios
    FOR EACH ROW EXECUTE FUNCTION presus.fn_auditoria_generica();

CREATE TRIGGER trg_auditoria_roles_usuario
    AFTER INSERT OR UPDATE OR DELETE ON presus.roles_usuario
    FOR EACH ROW EXECUTE FUNCTION presus.fn_auditoria_generica();

CREATE TRIGGER trg_auditoria_permisos
    AFTER INSERT OR UPDATE OR DELETE ON presus.permisos
    FOR EACH ROW EXECUTE FUNCTION presus.fn_auditoria_generica();

CREATE TRIGGER trg_auditoria_rol_permisos
    AFTER INSERT OR DELETE ON presus.rol_permisos
    FOR EACH ROW EXECUTE FUNCTION presus.fn_auditoria_rol_permisos();

CREATE TRIGGER trg_auditoria_solicitud
    AFTER INSERT OR UPDATE OR DELETE ON presus.solicitud
    FOR EACH ROW EXECUTE FUNCTION presus.fn_auditoria_generica();

CREATE TRIGGER trg_auditoria_actas
    AFTER INSERT OR UPDATE OR DELETE ON presus.actas
    FOR EACH ROW EXECUTE FUNCTION presus.fn_auditoria_generica();

CREATE TRIGGER trg_auditoria_evaluaciones_finales
    AFTER INSERT OR UPDATE OR DELETE ON presus.evaluaciones_finales
    FOR EACH ROW EXECUTE FUNCTION presus.fn_auditoria_generica();

-- ── Nuevo permiso, siguiendo el mismo catálogo dinámico de V13 ────────────────
INSERT INTO presus.permisos (id, codigo, nombre, categoria, descripcion) VALUES
    (19, 'AUDITORIA_VER', 'Ver auditoría', 'Administración', 'Consultar el historial de quién creó, modificó, aprobó o eliminó información y cuándo')
ON CONFLICT (id) DO NOTHING;

INSERT INTO presus.rol_permisos (rol_id, permiso_id)
SELECT 1, p.id FROM presus.permisos p WHERE p.codigo = 'AUDITORIA_VER'
ON CONFLICT DO NOTHING;
