-- =============================================================================
-- V19__historial_actas_y_reportes.sql
-- Módulo 2 (Gestión e historial de actas) + soporte del módulo de reportes.
--
-- El Acta no tenía estado explícito: su "estado" se derivaba de las banderas
-- firmada_* (ver Acta.actualizarEstadoFirma / ActaServiceImpl.firmarActa). Para el
-- flujo GENERADA -> REVISADA -> FINALIZADA que pide el requerimiento se agrega:
--   1. Un catálogo presus.estados_acta  (mismo patrón que estados_solicitud de V1
--      y estados_academicos de V16: id SMALLINT explícito, codigo UNIQUE, orden).
--   2. La columna presus.actas.estado_id -> FK a estados_acta, con backfill desde
--      la bandera firmada (patrón idéntico a V16.estado_academico_id).
--   3. presus.historial_estados_acta -> tabla de trazabilidad análoga a
--      historial_estados_solicitud (V1), ampliada con accion + rol_usuario para el
--      timeline del requerimiento. La escribe ActaServiceImpl en cada transición.
--
-- La auditoría genérica de V15 (trigger trg_auditoria_actas con to_jsonb(OLD/NEW))
-- se CONSERVA como respaldo a nivel de base: si algo escribe directo a actas sin
-- pasar por el backend, igual queda registrado.
--
-- Migración idempotente y válida desde una base limpia (IF NOT EXISTS / ON CONFLICT).
-- =============================================================================

-- ── 1. Catálogo de estados de acta ───────────────────────────────────────────
CREATE TABLE IF NOT EXISTS presus.estados_acta (
    id     SMALLINT    NOT NULL,
    codigo VARCHAR(30) NOT NULL UNIQUE,
    nombre VARCHAR(80) NOT NULL,
    orden  SMALLINT    NOT NULL,
    PRIMARY KEY (id)
);

INSERT INTO presus.estados_acta (id, codigo, nombre, orden) VALUES
    (1, 'GENERADA',   'Generada',   1),
    (2, 'REVISADA',   'Revisada',   2),
    (3, 'OBSERVADA',  'Observada',  3),
    (4, 'FINALIZADA', 'Finalizada', 4),
    (5, 'ANULADA',    'Anulada',    5)
ON CONFLICT (id) DO NOTHING;

-- ── 2. actas.estado_id (backfill desde la bandera firmada) ────────────────────
ALTER TABLE presus.actas ADD COLUMN IF NOT EXISTS estado_id SMALLINT;
UPDATE presus.actas SET estado_id = CASE WHEN firmada THEN 4 ELSE 1 END WHERE estado_id IS NULL;
ALTER TABLE presus.actas ALTER COLUMN estado_id SET DEFAULT 1;
ALTER TABLE presus.actas ALTER COLUMN estado_id SET NOT NULL;

DO $$ BEGIN
    ALTER TABLE presus.actas
        ADD CONSTRAINT fk_actas_estado FOREIGN KEY (estado_id) REFERENCES presus.estados_acta (id);
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

CREATE INDEX IF NOT EXISTS ix_actas_estado ON presus.actas (estado_id);

-- ── 3. Historial de transiciones de estado del acta ──────────────────────────
CREATE TABLE IF NOT EXISTS presus.historial_estados_acta (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY,
    acta_id            BIGINT       NOT NULL,
    estado_anterior_id SMALLINT,
    estado_nuevo_id    SMALLINT     NOT NULL,
    usuario_id         BIGINT,
    rol_usuario        VARCHAR(30),
    accion             VARCHAR(30)  NOT NULL,
    comentario         TEXT,
    fecha_cambio       TIMESTAMP(6) NOT NULL DEFAULT now(),
    PRIMARY KEY (id),
    CONSTRAINT fk_hist_acta_acta      FOREIGN KEY (acta_id)            REFERENCES presus.actas (id) ON DELETE CASCADE,
    CONSTRAINT fk_hist_acta_est_ant   FOREIGN KEY (estado_anterior_id) REFERENCES presus.estados_acta (id),
    CONSTRAINT fk_hist_acta_est_nuevo FOREIGN KEY (estado_nuevo_id)    REFERENCES presus.estados_acta (id),
    CONSTRAINT fk_hist_acta_usuario   FOREIGN KEY (usuario_id)         REFERENCES presus.usuarios (id)
);

CREATE INDEX IF NOT EXISTS ix_historial_acta_acta_fecha ON presus.historial_estados_acta (acta_id, fecha_cambio DESC);
CREATE INDEX IF NOT EXISTS ix_historial_acta_usuario     ON presus.historial_estados_acta (usuario_id);

-- Semilla del historial para las actas ya existentes: un evento CREAR con el estado
-- actual. usuario_id/rol NULL = "sin autor identificado" (registro histórico), mismo
-- criterio que auditoria.usuario_id (V15) cuando nadie fijó el GUC de sesión.
INSERT INTO presus.historial_estados_acta
    (acta_id, estado_anterior_id, estado_nuevo_id, usuario_id, rol_usuario, accion, comentario, fecha_cambio)
SELECT a.id, NULL, a.estado_id, NULL, NULL, 'CREAR',
       'Registro histórico generado por la migración V19', a.fecha_generacion::timestamp
FROM presus.actas a
WHERE NOT EXISTS (SELECT 1 FROM presus.historial_estados_acta h WHERE h.acta_id = a.id);

-- ── 4. Permisos nuevos (mismo catálogo dinámico de V13) ──────────────────────
INSERT INTO presus.permisos (id, codigo, nombre, categoria, descripcion) VALUES
    (22, 'ACTAS_VER',           'Ver actas',             'Actas', 'Listar y consultar el detalle de las actas de pre-sustentación'),
    (23, 'ACTAS_VER_PROPIAS',   'Ver actas propias',     'Actas', 'Que un docente vea las actas de las pre-sustentaciones en las que es tutor o jurado'),
    (24, 'ACTA_HISTORIAL_VER',  'Ver historial de acta', 'Actas', 'Consultar el historial de cambios de estado de un acta'),
    (25, 'ACTA_ESTADO_CAMBIAR', 'Cambiar estado de acta','Actas', 'Cambiar el estado de un acta (revisar, observar, finalizar, anular) según las reglas del proceso'),
    (26, 'ACTAS_GESTIONAR',     'Gestionar actas',       'Actas', 'Gestión administrativa completa de actas: buscar, filtrar, corregir y cambiar estado')
ON CONFLICT (id) DO NOTHING;

-- ADMIN: todos los permisos de actas
INSERT INTO presus.rol_permisos (rol_id, permiso_id)
SELECT 1, p.id FROM presus.permisos p
WHERE p.codigo IN ('ACTAS_VER','ACTAS_VER_PROPIAS','ACTA_HISTORIAL_VER','ACTA_ESTADO_CAMBIAR','ACTAS_GESTIONAR')
ON CONFLICT DO NOTHING;

-- COORDINADOR: ver, ver historial y cambiar estado (revisión académica);
-- NO gestión administrativa completa (ACTAS_GESTIONAR queda solo para ADMIN).
INSERT INTO presus.rol_permisos (rol_id, permiso_id)
SELECT 3, p.id FROM presus.permisos p
WHERE p.codigo IN ('ACTAS_VER','ACTA_HISTORIAL_VER','ACTA_ESTADO_CAMBIAR')
ON CONFLICT DO NOTHING;

-- DOCENTE: solo sus propias actas y el historial de esas (el service aplica el
-- filtro por propiedad; el permiso solo habilita la funcionalidad).
INSERT INTO presus.rol_permisos (rol_id, permiso_id)
SELECT 2, p.id FROM presus.permisos p
WHERE p.codigo IN ('ACTAS_VER_PROPIAS','ACTA_HISTORIAL_VER')
ON CONFLICT DO NOTHING;

-- Nota: los reportes de coordinador/administrador reutilizan el permiso REPORTES_VER
-- (id 18, V13) que ADMIN y COORDINADOR ya poseen -- no se crea un permiso nuevo.
