-- V20__centro_orientacion_titulacion.sql
-- Nuevas tablas para el módulo del Centro de Orientación para la Titulación

-- 1. Tabla intermedia para hacer configurable la relación entre Carreras y Líneas de Investigación
CREATE TABLE presus.carrera_linea_investigacion (
    carrera_id INTEGER NOT NULL REFERENCES presus.carreras(id) ON DELETE CASCADE,
    linea_investigacion_id INTEGER NOT NULL REFERENCES presus.lineas_investigacion(id) ON DELETE CASCADE,
    PRIMARY KEY (carrera_id, linea_investigacion_id)
);

CREATE TRIGGER trg_auditoria_carrera_linea_investigacion
    AFTER INSERT OR UPDATE OR DELETE ON presus.carrera_linea_investigacion
    FOR EACH ROW EXECUTE FUNCTION presus.fn_auditoria_generica();

-- 2. Tabla para el catálogo de ideas de temas de titulación propuestos
CREATE TABLE presus.temas_propuestos (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    titulo VARCHAR(500) NOT NULL,
    problema TEXT,
    objetivo_general TEXT,
    objetivos_especificos TEXT,
    justificacion TEXT,
    beneficiarios TEXT,
    nivel_dificultad VARCHAR(50),
    carrera_id INTEGER REFERENCES presus.carreras(id) ON DELETE CASCADE,
    linea_investigacion_id INTEGER REFERENCES presus.lineas_investigacion(id) ON DELETE CASCADE,
    area_id INTEGER REFERENCES presus.areas_tematicas(id) ON DELETE CASCADE
);

CREATE TRIGGER trg_auditoria_temas_propuestos
    AFTER INSERT OR UPDATE OR DELETE ON presus.temas_propuestos
    FOR EACH ROW EXECUTE FUNCTION presus.fn_auditoria_generica();

-- 3. Tabla para el centro de recursos y guías de titulación
CREATE TABLE presus.recursos_titulacion (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    titulo VARCHAR(255) NOT NULL,
    categoria VARCHAR(100) NOT NULL,
    url_archivo VARCHAR(500) NOT NULL,
    carrera_id INTEGER REFERENCES presus.carreras(id) ON DELETE SET NULL
);

CREATE TRIGGER trg_auditoria_recursos_titulacion
    AFTER INSERT OR UPDATE OR DELETE ON presus.recursos_titulacion
    FOR EACH ROW EXECUTE FUNCTION presus.fn_auditoria_generica();

-- 4. Tabla para guardar la ruta de titulación y checklist de cada estudiante
CREATE TABLE presus.progreso_estudiante (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    estudiante_id INTEGER NOT NULL REFERENCES presus.estudiante(id) ON DELETE CASCADE UNIQUE,
    pasos_json JSONB NOT NULL DEFAULT '{}'::jsonb
);

CREATE TRIGGER trg_auditoria_progreso_estudiante
    AFTER INSERT OR UPDATE OR DELETE ON presus.progreso_estudiante
    FOR EACH ROW EXECUTE FUNCTION presus.fn_auditoria_generica();

-- 5. Tabla para que los estudiantes guarden los temas propuestos que les interesaron
CREATE TABLE presus.temas_guardados (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    estudiante_id INTEGER NOT NULL REFERENCES presus.estudiante(id) ON DELETE CASCADE,
    tema_propuesto_id INTEGER NOT NULL REFERENCES presus.temas_propuestos(id) ON DELETE CASCADE,
    fecha_guardado TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (estudiante_id, tema_propuesto_id)
);

CREATE TRIGGER trg_auditoria_temas_guardados
    AFTER INSERT OR UPDATE OR DELETE ON presus.temas_guardados
    FOR EACH ROW EXECUTE FUNCTION presus.fn_auditoria_generica();
