-- =============================================================================
-- V28__gestion_respaldos_cronograma.sql
-- Fase 1 del plan de respaldos (ver docs/basedatos/PLAN-RESPALDOS-RECUPERACION.md):
-- convierte el apartado "Gestión de Respaldos" de "generar copias a mano" en una
-- gestión con cronograma real:
--   - respaldo_config: una fila (singleton) con la programación del FULL automático
--     y la política de retención GFS (grandfather-father-son).
--   - respaldo_prueba_restauracion: bitácora de las pruebas de restauración
--     periódicas (obligatorias según el plan).
--
-- El tipo (FULL/DIFERENCIAL) y el origen (MANUAL/AUTOMATICO/EVENTO) de cada
-- respaldo NO viven aquí: van codificados en el nombre del archivo
-- (respaldo_<TIPO>_<ORIGEN>_<yyyyMMdd_HHmmss>.dump), para que el archivo siga
-- siendo la única fuente de verdad y no haya que sincronizar tabla <-> disco.
--
-- No se crea un permiso nuevo: se reutiliza BACKUPS_GESTIONAR (V27).
-- =============================================================================

CREATE TABLE presus.respaldo_config (
    id                 SMALLINT     NOT NULL DEFAULT 1,
    activo             BOOLEAN      NOT NULL DEFAULT TRUE,
    -- Expresión cron de Spring (6 campos: seg min hora dia mes dia-semana).
    -- Por defecto: domingo a las 23:00 (mínima actividad académica).
    cron               VARCHAR(120) NOT NULL DEFAULT '0 0 23 * * SUN',
    -- Retención GFS: cuántas copias AUTOMÁTICAS conservar en cada nivel.
    -- Las copias MANUAL y EVENTO nunca se borran automáticamente.
    retener_diarios    SMALLINT     NOT NULL DEFAULT 7,
    retener_semanales  SMALLINT     NOT NULL DEFAULT 5,
    retener_mensuales  SMALLINT     NOT NULL DEFAULT 12,
    actualizado_en     TIMESTAMP(6) NOT NULL DEFAULT now(),
    actualizado_por    VARCHAR(200),
    PRIMARY KEY (id),
    CONSTRAINT respaldo_config_singleton     CHECK (id = 1),
    CONSTRAINT respaldo_config_retener_pos   CHECK (retener_diarios >= 0 AND retener_semanales >= 0 AND retener_mensuales >= 0)
);

INSERT INTO presus.respaldo_config (id) VALUES (1) ON CONFLICT (id) DO NOTHING;

CREATE TABLE presus.respaldo_prueba_restauracion (
    id               BIGINT       GENERATED BY DEFAULT AS IDENTITY,
    respaldo_nombre  VARCHAR(255) NOT NULL,
    fecha            TIMESTAMP(6) NOT NULL DEFAULT now(),
    resultado        VARCHAR(20)  NOT NULL,   -- EXITOSA | FALLIDA
    responsable      VARCHAR(200),
    notas            TEXT,
    PRIMARY KEY (id),
    CONSTRAINT respaldo_prueba_resultado CHECK (resultado IN ('EXITOSA', 'FALLIDA'))
);

CREATE INDEX ix_respaldo_prueba_fecha ON presus.respaldo_prueba_restauracion (fecha DESC);

-- Auditoría: la configuración del cronograma es una operación administrativa sensible.
CREATE TRIGGER trg_auditoria_respaldo_config
    AFTER INSERT OR UPDATE OR DELETE ON presus.respaldo_config
    FOR EACH ROW EXECUTE FUNCTION presus.fn_auditoria_generica();
