-- =============================================================================
-- V31__retencion_y_supresion_datos_personales.sql
-- RNF-19 (fase 7): retencion y supresion de datos personales (Ley Organica de
-- Proteccion de Datos Personales del Ecuador). Dos tablas nuevas, ninguna
-- expuesta como via de borrado de la bitacora via API (ver RNF-18):
--
--   - depuracion_bitacora_log: traza de cada corrida del expurgo automatico de
--     presus.auditoria (cuantas entradas, hasta que fecha). La depuracion en si
--     la ejecuta una tarea programada (DepuracionBitacoraScheduler), nunca un
--     endpoint -- RNF-18 prohibe que la API borre/modifique la bitacora, no que
--     una tarea de sistema, sin entrada de usuario, aplique la politica de
--     retencion ya declarada en docs/etica/RETENCION-DATOS.md.
--
--   - solicitud_supresion: bitacora de las solicitudes de supresion del
--     titular y su resolucion. Deliberadamente NO guarda el dato personal
--     suprimido (la paradoja del criterio: el registro de la supresion no
--     puede contener lo suprimido) -- solo el id del usuario (que sigue
--     existiendo, seudonimizado, no borrado: ver el rationale de RNF-19 en el
--     SRS sobre por que un expediente academico se seudonimiza y no se borra).
-- =============================================================================

CREATE TABLE presus.depuracion_bitacora_log (
    id                  BIGINT       GENERATED BY DEFAULT AS IDENTITY,
    fecha_ejecucion     TIMESTAMP(6) NOT NULL DEFAULT now(),
    entradas_eliminadas INTEGER      NOT NULL,
    fecha_corte         TIMESTAMP(6) NOT NULL,
    PRIMARY KEY (id)
);

CREATE INDEX ix_depuracion_bitacora_log_fecha ON presus.depuracion_bitacora_log (fecha_ejecucion DESC);

CREATE TABLE presus.solicitud_supresion (
    id                BIGINT       GENERATED BY DEFAULT AS IDENTITY,
    usuario_id        BIGINT       NOT NULL REFERENCES presus.usuarios(id),
    fecha_solicitud   TIMESTAMP(6) NOT NULL DEFAULT now(),
    estado            VARCHAR(20)  NOT NULL DEFAULT 'PENDIENTE',
    tipo_resolucion   VARCHAR(20),
    resuelto_por      BIGINT       REFERENCES presus.usuarios(id),
    fecha_resolucion  TIMESTAMP(6),
    notas             TEXT,
    PRIMARY KEY (id),
    CONSTRAINT solicitud_supresion_estado_chk
        CHECK (estado IN ('PENDIENTE', 'RESUELTA', 'RECHAZADA')),
    CONSTRAINT solicitud_supresion_tipo_resolucion_chk
        CHECK (tipo_resolucion IS NULL OR tipo_resolucion IN ('SEUDONIMIZACION', 'RECHAZADA'))
);

CREATE INDEX ix_solicitud_supresion_usuario ON presus.solicitud_supresion (usuario_id);
CREATE INDEX ix_solicitud_supresion_estado ON presus.solicitud_supresion (estado);

-- Auditoria: la propia solicitud/resolucion de supresion es una operacion administrativa
-- sensible y queda registrada por el mismo trigger generico que ya cubre el resto (V15).
CREATE TRIGGER trg_auditoria_solicitud_supresion
    AFTER INSERT OR UPDATE ON presus.solicitud_supresion
    FOR EACH ROW EXECUTE FUNCTION presus.fn_auditoria_generica();
